FROM node:lts-buster
RUN git clone https://gh repo clone corneh-bot/corneh
WORKDIR /root/ikmalvin
RUN npm install && npm install -g pm2 || yarn install --network-concurrency 1
COPY . .
EXPOSE 9000
CMD ["npm", "start"]
